package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbConversionId generated by hbm2java
 */
@Embeddable
public class TbConversionId implements java.io.Serializable {

	private int idMeasure1;
	private int idMeasure2;
	private int multiplier;

	public TbConversionId() {
	}

	public TbConversionId(int idMeasure1, int idMeasure2, int multiplier) {
		this.idMeasure1 = idMeasure1;
		this.idMeasure2 = idMeasure2;
		this.multiplier = multiplier;
	}

	@Column(name = "idMeasure1", nullable = false)
	public int getIdMeasure1() {
		return this.idMeasure1;
	}

	public void setIdMeasure1(int idMeasure1) {
		this.idMeasure1 = idMeasure1;
	}

	@Column(name = "idMeasure2", nullable = false)
	public int getIdMeasure2() {
		return this.idMeasure2;
	}

	public void setIdMeasure2(int idMeasure2) {
		this.idMeasure2 = idMeasure2;
	}

	@Column(name = "multiplier", nullable = false, precision = 5, scale = 0)
	public int getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(int multiplier) {
		this.multiplier = multiplier;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbConversionId))
			return false;
		TbConversionId castOther = (TbConversionId) other;

		return (this.getIdMeasure1() == castOther.getIdMeasure1())
				&& (this.getIdMeasure2() == castOther.getIdMeasure2())
				&& (this.getMultiplier() == castOther.getMultiplier());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMeasure1();
		result = 37 * result + this.getIdMeasure2();
		result = 37 * result + this.getMultiplier();
		return result;
	}

}
