package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbComments generated by hbm2java
 */
@Entity
@Table(name = "TbComments", catalog = "YMR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idRecipe", "order" }))
public class TbComments implements java.io.Serializable {

	private Integer idComment;
	private TbUsers user;
	private TbRecipes recipe;
	private int order;
	private String comment;
	private Date commentCreated;

	public TbComments() {
	}

	public TbComments(TbUsers user, TbRecipes recipe, int order, String comment,
			Date commentCreated) {
		this.user = user;
		this.recipe = recipe;
		this.order = order;
		this.comment = comment;
		this.commentCreated = commentCreated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idComment", unique = true, nullable = false)
	public Integer getIdComment() {
		return this.idComment;
	}

	public void setIdComment(Integer idComment) {
		this.idComment = idComment;
	}

	@ManyToOne
	@JoinColumn(name="idUser")
	public TbUsers getUser() {
		return user;
	}

	public void setUser(TbUsers user) {
		this.user = user;
	}
	
	@ManyToOne
	@JoinColumn(name="idRecipe")
	public TbRecipes getRecipe() {
		return recipe;
	}

	public void setRecipe(TbRecipes recipe) {
		this.recipe = recipe;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "comment", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "commentCreated", nullable = false, length = 19)
	public Date getCommentCreated() {
		return this.commentCreated;
	}

	public void setCommentCreated(Date commentCreated) {
		this.commentCreated = commentCreated;
	}

}
