package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbCountries generated by hbm2java
 */
@Entity
@Table(name = "TbCountries", catalog = "YMR")
public class TbCountries implements java.io.Serializable {

	private Integer idCountry;
	private TbLanguages language;
	private int idLanguage;
	private String countryName;
	private Collection<TbUsers> users = new ArrayList<TbUsers>();
	
	public TbCountries() {
	}

	public TbCountries(int idLanguage, String countryName) {
		this.idLanguage = idLanguage;
		this.countryName = countryName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCountry", unique = true, nullable = false)
	public Integer getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(Integer idCountry) {
		this.idCountry = idCountry;
	}

	@OneToOne
	@JoinColumn(name="idLanguage")
	public TbLanguages getLanguage() {
		return language;
	}

	public void setLanguage(TbLanguages language) {
		this.language = language;
	}

	@Column(name = "idLanguage", nullable = false)
	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	@Column(name = "countryName", nullable = false, length = 45)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@OneToMany(mappedBy="country")
	public Collection<TbUsers> getUsers() {
		return users;
	}

	public void setUsers(Collection<TbUsers> users) {
		this.users = users;
	}
}
