package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TbFollowers generated by hbm2java
 */
@Entity
@Table(name = "TbFollowers", catalog = "YMR", uniqueConstraints = @UniqueConstraint(columnNames = {
		"idFollowing", "idFollower" }))
public class TbFollowers implements java.io.Serializable {

	private TbFollowersId id;

	public TbFollowers() {
	}

	public TbFollowers(TbFollowersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idFollowing", column = @Column(name = "idFollowing", nullable = false)),
			@AttributeOverride(name = "idFollower", column = @Column(name = "idFollower", nullable = false)) })
	public TbFollowersId getId() {
		return this.id;
	}

	public void setId(TbFollowersId id) {
		this.id = id;
	}

}
