package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbFollowersId generated by hbm2java
 */
@Embeddable
public class TbFollowersId implements java.io.Serializable {

	private int idFollowing;
	private int idFollower;

	public TbFollowersId() {
	}

	public TbFollowersId(int idFollowing, int idFollower) {
		this.idFollowing = idFollowing;
		this.idFollower = idFollower;
	}

	@Column(name = "idFollowing", nullable = false)
	public int getIdFollowing() {
		return this.idFollowing;
	}

	public void setIdFollowing(int idFollowing) {
		this.idFollowing = idFollowing;
	}

	@Column(name = "idFollower", nullable = false)
	public int getIdFollower() {
		return this.idFollower;
	}

	public void setIdFollower(int idFollower) {
		this.idFollower = idFollower;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbFollowersId))
			return false;
		TbFollowersId castOther = (TbFollowersId) other;

		return (this.getIdFollowing() == castOther.getIdFollowing())
				&& (this.getIdFollower() == castOther.getIdFollower());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFollowing();
		result = 37 * result + this.getIdFollower();
		return result;
	}

}
