package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TbHashtags generated by hbm2java
 */
@Entity
@Table(name = "TbHashtags", catalog = "YMR", uniqueConstraints = @UniqueConstraint(columnNames = "hashtag"))
public class TbHashtags implements java.io.Serializable {

	private Integer idHashtag;
	private String hashtag;

	public TbHashtags() {
	}

	public TbHashtags(String hashtag) {
		this.hashtag = hashtag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idHashtag", unique = true, nullable = false)
	public Integer getIdHashtag() {
		return this.idHashtag;
	}

	public void setIdHashtag(Integer idHashtag) {
		this.idHashtag = idHashtag;
	}

	@Column(name = "hashtag", unique = true, nullable = false, length = 45)
	public String getHashtag() {
		return this.hashtag;
	}

	public void setHashtag(String hashtag) {
		this.hashtag = hashtag;
	}

}
