package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbImages generated by hbm2java
 */
@Entity
@Table(name = "TbImages", catalog = "YMR")
public class TbImages implements java.io.Serializable {

	private Integer idImage;
	private int idRecipe;
	private String imageUrl;

	public TbImages() {
	}

	public TbImages(int idRecipe, String imageUrl) {
		this.idRecipe = idRecipe;
		this.imageUrl = imageUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idImage", unique = true, nullable = false)
	public Integer getIdImage() {
		return this.idImage;
	}

	public void setIdImage(Integer idImage) {
		this.idImage = idImage;
	}

	@Column(name = "idRecipe", nullable = false)
	public int getIdRecipe() {
		return this.idRecipe;
	}

	public void setIdRecipe(int idRecipe) {
		this.idRecipe = idRecipe;
	}

	@Column(name = "imageURL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
