package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbLanguages generated by hbm2java
 */
@Entity
@Table(name = "TbLanguages", catalog = "YMR")
public class TbLanguages implements java.io.Serializable {

	private Integer idLanguage;
	private String language;

	public TbLanguages() {
	}

	public TbLanguages(String language) {
		this.language = language;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLanguage", unique = true, nullable = false)
	public Integer getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(Integer idLanguage) {
		this.idLanguage = idLanguage;
	}

	@Column(name = "language", nullable = false, length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
