package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbLikesId generated by hbm2java
 */
@Embeddable
public class TbLikesId implements java.io.Serializable {

	private int idRecipe;
	private int idUser;

	public TbLikesId() {
	}

	public TbLikesId(int idRecipe, int idUser) {
		this.idRecipe = idRecipe;
		this.idUser = idUser;
	}

	@Column(name = "idRecipe", nullable = false)
	public int getIdRecipe() {
		return this.idRecipe;
	}

	public void setIdRecipe(int idRecipe) {
		this.idRecipe = idRecipe;
	}

	@Column(name = "idUser", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbLikesId))
			return false;
		TbLikesId castOther = (TbLikesId) other;

		return (this.getIdRecipe() == castOther.getIdRecipe())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRecipe();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
