package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbMeasures generated by hbm2java
 */
@Entity
@Table(name = "TbMeasures", catalog = "YMR")
public class TbMeasures implements java.io.Serializable {

	private Integer idMeasure;
	private int idCountry;
	private TbMeasureTypes measureType;
	private int idMeasureType;
	private String measureName;

	public TbMeasures() {
	}

	public TbMeasures(int idCountry, TbMeasureTypes measureType, String measureName) {
		this.idCountry = idCountry;
		this.measureType = measureType;
		this.measureName = measureName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMeasure", unique = true, nullable = false)
	public Integer getIdMeasure() {
		return this.idMeasure;
	}

	public void setIdMeasure(Integer idMeasure) {
		this.idMeasure = idMeasure;
	}

	@Column(name = "idCountry", nullable = false)
	public int getIdCountry() {
		return this.idCountry;
	}

	public void setIdCountry(int idCountry) {
		this.idCountry = idCountry;
	}

	@ManyToOne
	@JoinColumn(name="idMeasureType")
	public TbMeasureTypes getMeasureType() {
		return measureType;
	}

	public void setMeasureType(TbMeasureTypes measureType) {
		this.measureType = measureType;
	}

	@Column(name = "measureName", nullable = false, length = 45)
	public String getMeasureName() {
		return this.measureName;
	}

	public void setMeasureName(String measureName) {
		this.measureName = measureName;
	}

	
}
