package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbMeasureTypes generated by hbm2java
 */
@Entity
@Table(name = "TbMeasureTypes", catalog = "YMR")
public class TbMeasureTypes implements java.io.Serializable {

	private Integer idMeasureType;
	private String measureType;
	
	private Collection<TbMeasures> measures = new ArrayList<TbMeasures>();
	
	public TbMeasureTypes() {
	}

	public TbMeasureTypes(String measureType) {
		this.measureType = measureType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMeasureType", unique = true, nullable = false)
	public Integer getIdMeasureType() {
		return this.idMeasureType;
	}

	public void setIdMeasureType(Integer idMeasureType) {
		this.idMeasureType = idMeasureType;
	}

	@Column(name = "measureType", nullable = false, length = 45)
	public String getMeasureType() {
		return this.measureType;
	}

	public void setMeasureType(String measureType) {
		this.measureType = measureType;
	}
	
	@OneToMany(mappedBy="measureType")
	public Collection<TbMeasures> getMeasures() {
		return measures;
	}

	public void setMeasures(Collection<TbMeasures> measures) {
		this.measures = measures;
	}

	
}
