package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTips generated by hbm2java
 */
@Entity
@Table(name = "TbTips", catalog = "YMR")
public class TbRecipeTips implements java.io.Serializable {

	private Integer idTips;
	private TbRecipes recipe;
	private String tipsDescription;

	public TbRecipeTips() {
	}

	public TbRecipeTips(TbRecipes recipe, String tipsDescription) {
		this.recipe = recipe;
		this.tipsDescription = tipsDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTips", unique = true, nullable = false)
	public Integer getIdTips() {
		return this.idTips;
	}

	public void setIdTips(Integer idTips) {
		this.idTips = idTips;
	}

	@Column(name = "tipsDescription", nullable = false)
	public String getTipsDescription() {
		return this.tipsDescription;
	}

	public void setTipsDescription(String tipsDescription) {
		this.tipsDescription = tipsDescription;
	}

	@ManyToOne
	@JoinColumn(name="Recipe")
	public TbRecipes getRecipe() {
		return recipe;
	}

	public void setRecipe(TbRecipes recipe) {
		this.recipe = recipe;
	}

	
}
