package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbRecipeParts generated by hbm2java
 */
@Entity
@Table(name = "TbRecipeParts", catalog = "YMR")
public class TbRecipeParts implements java.io.Serializable {

	private Integer idRecipePart;
	private TbRecipes recipe;
	private String recipePartName;

	public TbRecipeParts() {
	}

	public TbRecipeParts(TbRecipes recipe) {
		this.recipe = recipe;
	}

	public TbRecipeParts(TbRecipes recipe, String recipePartName) {
		this.recipe = recipe;
		this.recipePartName = recipePartName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRecipePart", unique = true, nullable = false)
	public Integer getIdRecipePart() {
		return this.idRecipePart;
	}

	public void setIdRecipePart(Integer idRecipePart) {
		this.idRecipePart = idRecipePart;
	}

	@Column(name = "recipePartName")
	public String getRecipePartName() {
		return this.recipePartName;
	}

	public void setRecipePartName(String recipePartName) {
		this.recipePartName = recipePartName;
	}

	@ManyToOne
	@JoinColumn(name="idRecipe")
	public TbRecipes getRecipe() {
		return recipe;
	}

	public void setRecipe(TbRecipes recipe) {
		this.recipe = recipe;
	}

	
}
