package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbRecipeSteps generated by hbm2java
 */
@Entity
@Table(name = "TbRecipeSteps", catalog = "YMR")
public class TbRecipeSteps implements java.io.Serializable {

	private Integer idRecipeStep;
	private TbRecipes recipe;
	private String recipeStepTitle;
	private String recipeStepDescription;
	private int recipeStepOrder;
	
	private Collection<TbRecipeStepTips> recipeStepTips = new ArrayList<TbRecipeStepTips>();
	
	public TbRecipeSteps() {
	}

	public TbRecipeSteps(TbRecipes recipe, String recipeStepDescription,
			int recipeStepOrder) {
		this.recipe = recipe;
		this.recipeStepDescription = recipeStepDescription;
		this.recipeStepOrder = recipeStepOrder;
	}

	public TbRecipeSteps(TbRecipes recipe, String recipeStepTitle,
			String recipeStepDescription, int recipeStepOrder) {
		this.recipe = recipe;
		this.recipeStepTitle = recipeStepTitle;
		this.recipeStepDescription = recipeStepDescription;
		this.recipeStepOrder = recipeStepOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRecipeStep", unique = true, nullable = false)
	public Integer getIdRecipeStep() {
		return this.idRecipeStep;
	}

	public void setIdRecipeStep(Integer idRecipeStep) {
		this.idRecipeStep = idRecipeStep;
	}

	@Column(name = "RecipeStepTitle")
	public String getRecipeStepTitle() {
		return this.recipeStepTitle;
	}

	public void setRecipeStepTitle(String recipeStepTitle) {
		this.recipeStepTitle = recipeStepTitle;
	}

	@Column(name = "RecipeStepDescription", nullable = false)
	public String getRecipeStepDescription() {
		return this.recipeStepDescription;
	}

	public void setRecipeStepDescription(String recipeStepDescription) {
		this.recipeStepDescription = recipeStepDescription;
	}

	@Column(name = "RecipeStepOrder", nullable = false)
	public int getRecipeStepOrder() {
		return this.recipeStepOrder;
	}

	public void setRecipeStepOrder(int recipeStepOrder) {
		this.recipeStepOrder = recipeStepOrder;
	}

	@ManyToOne
	@JoinColumn(name="idRecipe")
	public TbRecipes getRecipe() {
		return recipe;
	}

	public void setRecipe(TbRecipes recipe) {
		this.recipe = recipe;
	}

	@OneToMany(mappedBy="recipeStep")
	public Collection<TbRecipeStepTips> getRecipeStepTips() {
		return recipeStepTips;
	}

	public void setRecipeStepTips(Collection<TbRecipeStepTips> recipeStepTips) {
		this.recipeStepTips = recipeStepTips;
	}
	
	
}
