package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTags generated by hbm2java
 */
@Entity
@Table(name = "TbTags", catalog = "YMR")
public class TbTags implements java.io.Serializable {

	private Integer idTag;
	private TbTagTypes tagType;
	private String tagName;

	public TbTags() {
	}

	public TbTags(TbTagTypes tagType, String tagName) {
		this.tagType = tagType;
		this.tagName = tagName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTag", unique = true, nullable = false)
	public Integer getIdTag() {
		return this.idTag;
	}

	public void setIdTag(Integer idTag) {
		this.idTag = idTag;
	}

	@Column(name = "tagName", nullable = false)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@ManyToOne
	@JoinColumn(name="idTagType")
	public TbTagTypes getTagType() {
		return tagType;
	}

	public void setTagType(TbTagTypes tagType) {
		this.tagType = tagType;
	}

	
}
