package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTagTypes generated by hbm2java
 */
@Entity
@Table(name = "TbTagTypes", catalog = "YMR")
public class TbTagTypes implements java.io.Serializable {

	private Integer idTagType;
	private String tagType;
	private Collection<TbTags> tags = new ArrayList<TbTags>(); 
	
	public TbTagTypes() {
	}

	public TbTagTypes(String tagType) {
		this.tagType = tagType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTagType", unique = true, nullable = false)
	public Integer getIdTagType() {
		return this.idTagType;
	}

	public void setIdTagType(Integer idTagType) {
		this.idTagType = idTagType;
	}

	@Column(name = "tagType", nullable = false)
	public String getTagType() {
		return this.tagType;
	}

	public void setTagType(String tagType) {
		this.tagType = tagType;
	}

	@OneToMany(mappedBy="tagType")
	public Collection<TbTags> getTags() {
		return tags;
	}

	public void setTags(Collection<TbTags> tags) {
		this.tags = tags;
	}
	
	
}
