package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbUsers generated by hbm2java
 */
@Entity
@Table(name = "TbUsers", catalog = "YMR", uniqueConstraints = {
		@UniqueConstraint(columnNames = "userName"),
		@UniqueConstraint(columnNames = "userEmail") })
public class TbUsers implements java.io.Serializable {

	private Integer idUser;
	private TbCountries country;
	private TbUserTitles userTitle;
	private TbUserTypes userType;
	private String userName;
	private String userEmail;
	private Date userJoined;
	
	private Collection<TbComments> comments = new ArrayList<TbComments>();
	
	private Collection<TbRecipes> recipes = new ArrayList<TbRecipes>();
	
	private Collection<TbRecipes> recipesLiked = new ArrayList<TbRecipes>();
	
	public TbUsers() {
	}

	public TbUsers(TbCountries country, TbUserTitles userTitle, TbUserTypes userType, String userName,
			String userEmail, Date userJoined) {
		this.country = country;
		this.userTitle = userTitle;
		this.userType = userType;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userJoined = userJoined;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@ManyToOne
	@JoinColumn(name="idCountry")
	public TbCountries getCountry() {
		return country;
	}

	public void setCountry(TbCountries country) {
		this.country = country;
	}
	
	@ManyToOne
	@JoinColumn(name="idTitle")
	public TbUserTitles getUserTitle() {
		return userTitle;
	}

	public void setUserTitle(TbUserTitles userTitle) {
		this.userTitle = userTitle;
	}
	
	@ManyToOne
	@JoinColumn(name="idUserType")
	public TbUserTypes getUserType() {
		return userType;
	}

	public void setUserType(TbUserTypes userType) {
		this.userType = userType;
	}

	@Column(name = "userName", unique = true, nullable = false)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "userEmail", unique = true, nullable = false)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userJoined", nullable = false, length = 19)
	public Date getUserJoined() {
		return this.userJoined;
	}

	public void setUserJoined(Date userJoined) {
		this.userJoined = userJoined;
	}

	@OneToMany(mappedBy="user")
	public Collection<TbComments> getComments() {
		return comments;
	}

	public void setComments(Collection<TbComments> comments) {
		this.comments = comments;
	}

	@OneToMany(mappedBy="user")
	public Collection<TbRecipes> getRecipes() {
		return recipes;
	}

	public void setRecipes(Collection<TbRecipes> recipes) {
		this.recipes = recipes;
	}

	@ManyToMany
	@JoinTable(name="TbLikes", joinColumns=@JoinColumn(name="idUser"),
				inverseJoinColumns=@JoinColumn(name="idRecipe"))
	public Collection<TbRecipes> getRecipesLiked() {
		return recipesLiked;
	}

	public void setRecipesLiked(Collection<TbRecipes> recipesLiked) {
		this.recipesLiked = recipesLiked;
	}
	
	
	
	
}
