package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbUserTypes generated by hbm2java
 */
@Entity
@Table(name = "TbUserTypes", catalog = "YMR")
public class TbUserTypes implements java.io.Serializable {

	private Integer idUserType;
	private String userType;
	private Collection<TbUsers> users = new ArrayList<TbUsers>();
	
	public TbUserTypes() {
	}

	public TbUserTypes(String userType) {
		this.userType = userType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUserType", unique = true, nullable = false)
	public Integer getIdUserType() {
		return this.idUserType;
	}

	public void setIdUserType(Integer idUserType) {
		this.idUserType = idUserType;
	}

	@Column(name = "userType", nullable = false, length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@OneToMany(mappedBy="userType")
	public Collection<TbUsers> getUsers() {
		return users;
	}

	public void setUsers(Collection<TbUsers> users) {
		this.users = users;
	}
}
