package org.yves.project.ymr.model;

// default package
// Generated Nov 4, 2015 9:42:25 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbUserTitles generated by hbm2java
 */
@Entity
@Table(name = "TbUserTitles", catalog = "YMR")
public class TbUserTitles implements java.io.Serializable {

	private Integer idTitle;
	private String titleName;
	private Collection<TbUsers> users = new ArrayList<TbUsers>();
	
	public TbUserTitles() {
	}

	public TbUserTitles(String titleName) {
		this.titleName = titleName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTitle", unique = true, nullable = false)
	public Integer getIdTitle() {
		return this.idTitle;
	}

	public void setIdTitle(Integer idTitle) {
		this.idTitle = idTitle;
	}

	@Column(name = "titleName", nullable = false, length = 45)
	public String getTitleName() {
		return this.titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}
	
	@OneToMany(mappedBy="userTitle")
	public Collection<TbUsers> getUsers() {
		return users;
	}

	public void setUsers(Collection<TbUsers> users) {
		this.users = users;
	}

	
}
